#include "mcc_generated_files/mcc.h"
#include "protocol.h"
#include <stdlib.h>

#define DEVICE_ID "KXR94-2050"

#define OFFSET 512.0
#define G 204.8  // 1024/5.0 = 204.8 (steps/volt)

/*
 * get acceleration data from acceclerometer and convert it into G-unit value
 */
float get_accel(adc_channel_t ch) {
    float steps;
    ADC_SelectChannel(ch);
    ADC_StartConversion();
    while(!ADC_IsConversionDone());
    steps = (float)ADC_GetConversionResult();
    return (steps - OFFSET)/G;
}

void inv_handler(void) {
    float values[3];
    LATCbits.LATC7 ^= 1;
    values[0] = get_accel(channel_AN3);  // x-axis
    values[1] = get_accel(channel_AN7);  // y-axis
    values[2] = get_accel(channel_AN8);  // z-axis
    PROTOCOL_I2C_Send_float(3, values);
}

void main(void)
{    
    // Protocol initialization
    PROTOCOL_Initialize(DEVICE_ID, NULL, NULL, NULL, inv_handler, 0xff);

    // avoid using SYSTEM_Initialize() automatically generated by MCC,
    // because I2C1_Initialize() must be last in the initialization order
    PIN_MANAGER_Initialize();
    OSCILLATOR_Initialize();
    WDT_Initialize();
    ADC_Initialize();
    EUSART_Initialize();
    I2C1_Initialize();
    
    // Enable interrupt
    INTERRUPT_GlobalInterruptEnable();
    INTERRUPT_PeripheralInterruptEnable();
    
    // Infinite loop
    PROTOCOL_Loop();
}
